# Generated by Django 4.1.2 on 2022-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=640, null=True, upload_to='', width_field=640),
        ),
    ]
