# Generated by Django 4.1.2 on 2022-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='contract',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
