# Generated by Django 4.1.2 on 2022-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='walletID',
            field=models.CharField(default=12345678912, max_length=12),
            preserve_default=False,
        ),
    ]
